# Generated by Django 4.2.9 on 2024-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='title')),
                ('price', models.IntegerField()),
                ('year', models.DateField()),
                ('tank', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fuel_cons', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='manu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manu_name', models.CharField(max_length=50, verbose_name='title')),
                ('logo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('country', models.CharField(max_length=50, verbose_name='title')),
            ],
        ),
    ]
